name: Work FLow Hello, world!

on:
  push:
    branches: 
      - main
      - modulo3

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_job:
      name: Executando job de teste
      runs-on: ubuntu-latest
      steps:
      - name: CheckOut code
        uses: actions/checkout@v2

      - name: Excecutando um comando Simples
        run: echo "Olá, mundo!"
